# Generated by Django 6.0.4 on 2026-05-02 09:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512)),
                ('color', models.CharField(max_length=64)),
                ('storage', models.PositiveIntegerField()),
                ('producer', models.CharField(max_length=64)),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
                ('image_list', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=512), default=list)),
                ('product_code', models.CharField(max_length=32)),
                ('feedback_count', models.PositiveIntegerField(default=0)),
                ('diagonal', models.DecimalField(decimal_places=1, max_digits=3)),
                ('pixels', models.CharField(max_length=32)),
                ('details', models.JSONField(default=dict)),
            ],
        ),
    ]
