# Generated by Django 6.0.4 on 2026-05-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphone',
            name='diagonal',
            field=models.CharField(max_length=16),
        ),
    ]
