# Generated by Django 6.0.4 on 2026-05-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_iphone_diagonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphone',
            name='storage',
            field=models.CharField(max_length=16),
        ),
    ]
