# Generated by Django 6.0.4 on 2026-05-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_alter_iphone_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone',
            name='exist',
            field=models.BooleanField(default=False),
        ),
    ]
