# Generated by Django 6.0.4 on 2026-05-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0004_iphone_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphone',
            name='diagonal',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
